### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by DylanPiercey**
Please revert back to "dependencies" as the previous update breaks this module. (Try's to fetch mongodb @2.0).

### CODE REVIEW

**Comment by vkarpov15** [comment]
IMO it should just do `"peerDependencies": { "mongodb": "~1.4" }` - any reason why exactly 1.4.4?

**Comment by DylanPiercey** [comment]
Simply because It was what was in place previously and I did not have time to test other mongodb versions.

**Comment by vkarpov15** [comment]
Yeah as far as my casual inspection goes, 1.4.32 should work as well as 1.4.4. It's 2.0.23 and 2.0.24 that are breaking, which is unsurprising because of backwards breaking changes.

**Comment by DylanPiercey** [comment]
Well then it sounds fine. My only other concern is if it should be a peerdependency at all? I can't personally think of a situation where mongoskin would need to share the mongodb package much less an outdated version of the mongodb package.

Basically it seems to be forcing users to install two packages with an unknown advantage, could you shed some light?

**Comment by vkarpov15** [comment]
Hmm yeah looks like peerDependencies was recently introduced in 82894772eedb8dbb8cd93f5f6220d5ac5a84eaea , which is very strange because it seems like that should be something that requires a major version bump. The tradeoff is that, with the peerDependencies approach, we don't need a new version of mongoskin every time mongodb releases a patch - end users can plug in their own version of mongodb. The downside is that testing and debugging is more difficult, because then you have need to know the version of mongodb as well as the version of mongoskin to know what code is running. Standard shared vs static library tradeoff. I haven't looked into mongoskin enough to make a correct judgement, but from what I've seen so far it's a reasonably transparent wrapper around mongodb and so using peerDependencies seems like the right choice going forward. I'm open to arguments either way though.

**Comment by DylanPiercey** [comment]
I tend to agree that it makes sense as a peerDependency overall, but again it does break other packages. I would personally opt to wait for mongoskin to be using the current version of mongodb-native before allowing for peer dependencies.

**Pull request closed without merging**
